[phases.setup]
nixPkgs = ['python311', 'pip']
aptPkgs = ['python3-pip']

[phases.install]
cmds = [
    'python -m pip install --upgrade pip',
    'pip install -r requirements.txt'
]

[phases.build]
cmds = ['python manage.py collectstatic --noinput || true']

[start]
cmd = 'gunicorn  profile_card.wsgi --log-file - --bind 0.0.0.0:$PORT'